import type React from "react"
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "../globals.css"
import { AppSidebar } from "@/components/app-sidebar"
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar"
import { HeaderNav } from "@/components/header-nav"
import { ReduxProvider } from "@/lib/providers"
import { Toaster } from "@/components/ui/sonner"

const _geist = Geist({ subsets: ["latin"] })
const _geistMono = Geist_Mono({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="font-sans antialiased">
        <ReduxProvider>
          <SidebarProvider>
            <AppSidebar />
            <SidebarInset>
              <HeaderNav />
              <main className="flex-1 p-4">{children}</main>
            </SidebarInset>
            <Toaster />
          </SidebarProvider>
        </ReduxProvider>
      </body>
    </html>
  )
}
